### ISSUE TITLE
API no longer working: Says this server less function has crashed

### ISSUE THREAD

**Issue by g-rohit** [benborgers/potion#16]
It was all working fine till a couple of days back. Not sure what went wrong, someone please fix it.

![image](https://user-images.githubusercontent.com/43009327/136389134-a95e3027-129d-4a70-86a9-388f49335f47.png)

**Comment by benborgers** [comment]
Unfortunately I no longer plan on maintaining Potion, and suggest that you use the [official Notion API](https://developers.notion.com) instead. You’re totally welcome to submit a PR to Potion though! 

I've added a note in the readme: https://github.com/benborgers/potion/commit/03d82d2585847b36054a0f1894e020f806fc11c0
