### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by yodacom** [benborgers/potion#2]
Not really an issue just a question on how I might incorporate the video on Notion to my blog.
Until we have an API on Potion to use notion is there a way or idea of a way to have an iframe inserted in the code?  Or envelop this into next js?  Like embeding a youtube video? Just thinking out loud.....

All the best,

Jeremy

**Comment by benborgers** [comment]
Hi there! I just added support for the Notion video block (https://github.com/benborgers/potion/commit/8e4a3b88db9827d3af5c3ebfc91b1948af148437), so you should be able to use YouTube or Vimeo embeds now. Let me know if it works! 

By the way, regular iframe embeds to other websites are also supported. 

Also, if you have any other questions about using Potion with Next.js, don't hesitate to ask.

**Comment by yodacom** [comment]
Thanks Ben I will give it a try and report back.
