### ISSUE TITLE
What happens if the page is private

### ISSUE THREAD

**Issue by EURedBoy** [benborgers/potion#21]
Is there a way to add a notion key to retrive data either from private pages?

**Comment by benborgers** [comment]
This project used a reverse-engineered version of the Notion API before they had an official API, but I’ve built a version that uses the official API where you pass your own API key: [benborgers/tiny-notion-api](https://github.com/benborgers/tiny-notion-api)! 

The docs are nonexistent right now so if you have any questions on using it shoot me an email: benborgers@hey.com

**Comment by EURedBoy** [comment]
Thank you very much.
