### ISSUE TITLE
Images from Notion are not loading

### ISSUE THREAD

**Issue by hexandcube** [benborgers/potion#4]
Images from Notion have just stopped loading.
![image](https://user-images.githubusercontent.com/41151156/92321662-f3a29580-f02b-11ea-9da2-5a4857a50e52.png)

It looks like Notion now requires some additional information to load images from their servers.
![image](https://user-images.githubusercontent.com/41151156/92321674-19c83580-f02c-11ea-8e66-3db99a17f30a.png)

**Comment by benborgers** [comment]
Should be fixed by PR #5! 

Unfortunately people do have to re-build their sites if they're using a static site generator, since the underlying HTML has changed to make image URLs load. A redeployment of your Gatsby, Next.js, etc. project should fix the issue, if it's not fixed already.

**Comment by iandoesallthethings** [comment]
I'm still having trouble getting images to show up consistently using /html. It's displaying everything else correctly, but images only showed up the first couple of refreshes, then disappeared.

**Comment by benborgers** [comment]
@iandoesallthethings Hm, could you provide an example where images aren't loading correctly? I can't seem to reproduce it...

I thought for a moment that I could reproduce the error on my blog, but turns out that my Notion table somehow got un-shared with public access.

**Comment by iandoesallthethings** [comment]
Oh, I might have found it. I was putting a lot of small images on the same row. Long story short, I'm experimenting with devicons. 

If I put each icon (png) on its own row, they show up.

**Comment by iandoesallthethings** [comment]
@benborgers Is there any chance of SVG support?

**Comment by benborgers** [comment]
@iandoesallthethings Ah yeah, I think you'll need custom CSS to line up the images since Potion doesn't look inside of Notion rows/columns at the moment. Did you get SVGs working as well?

**Comment by iandoesallthethings** [comment]
Yeah, Actually. I loaded mostly SVGs (and some pngs where devicons didn't have a brand). If I arrange each one as its own block vertically in notion, they show up all on one line in HTML. 

It works great for my site as is. But is there a clean way to give them classes and/or ids to make it more flexible? They're all just plain img tags.

**Comment by benborgers** [comment]
Hmm I don't think there's a way to give them tags easily. If you need to label them, I'd probably go with a Notion table instead where one column is a name and one column is the uploaded image, and then putting together HTML yourself from that table.
