### ISSUE TITLE
Demo site failing

### ISSUE THREAD

**Issue by basilhayek** [benborgers/potion#9]
https://notion-to-website-static.glitch.me/
fails with 
A server error has occurred FUNCTION_INVOCATION_FAILED

Believe this might be related to the issue seen in another library:

https://github.com/splitbee/notion-api-worker/issues/38

**Comment by benborgers** [comment]
Yes! Thank you for letting me know about this - looks like Notion doesn't allow fetching more than 100 blocks now. I've added a loop to get all the blocks (if there are more than 100) in commit 8d24de36b374dfd69eccf485805c491e69d30dc7. Should be working again!
